### ISSUE TITLE
RuntimeError: [enforce fail at inline_container.cc:471] . PytorchStreamWriter failed writing file data/151: file write failed

### ISSUE THREAD

**Issue by bkowshik** [llm-efficiency-challenge/neurips_llm_efficiency_challenge#7]
Following the README, I tried building up the Docker image. But, get the following error in the weights conversion step.

```
 => ERROR [10/13] RUN python scripts/convert_hf_checkpoint.py --checkpoint_dir checkpoints/open-llama/7B --model_size 7B                                                       66.8s
------
 > [10/13] RUN python scripts/convert_hf_checkpoint.py --checkpoint_dir checkpoints/open-llama/7B --model_size 7B:
65.78 Initializing lit-llama
65.78 Saving to disk at checkpoints/lit-llama/7B
65.78 Processing checkpoints/open-llama/7B/pytorch_model-00001-of-00002.bin
65.78 Traceback (most recent call last):
65.78   File "/submission/scripts/convert_hf_checkpoint.py", line 136, in convert_hf_checkpoint
65.78     sd[sd_key] = saver.store_early(sd[sd_key])
65.78   File "/submission/lit_llama/utils.py", line 469, in store_early
65.78     return SavingProxyForTensor(tensor, self)
65.78   File "/submission/lit_llama/utils.py", line 387, in __init__
65.78     storage_proxy = SavingProxyForStorage(
65.78   File "/submission/lit_llama/utils.py", line 363, in __init__
65.78   File "/submission/lit_llama/utils.py", line 492, in _write_storage_and_return_key
65.78     storage_key = saver._write_storage_and_return_key(storage)
65.79     self.zipfile.write_record(name, storage.data_ptr(), num_bytes)
65.79 RuntimeError: [enforce fail at inline_container.cc:471] . PytorchStreamWriter failed writing file data/151: file write failed
65.79
65.79 During handling of the above exception, another exception occurred:
65.79
65.79 Traceback (most recent call last):
65.79   File "/submission/scripts/convert_hf_checkpoint.py", line 166, in <module>
65.79     CLI(convert_hf_checkpoint)
65.79   File "/opt/conda/lib/python3.10/site-packages/jsonargparse/_cli.py", line 85, in CLI
65.79     return _run_component(component, cfg_init)
65.79   File "/opt/conda/lib/python3.10/site-packages/jsonargparse/_cli.py", line 147, in _run_component
65.79     return component(**cfg)
65.79   File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
65.79     return func(*args, **kwargs)
65.79   File "/submission/scripts/convert_hf_checkpoint.py", line 88, in convert_hf_checkpoint
65.79     with incremental_save(output_dir / "lit-llama.pth") as saver:
65.79   File "/submission/lit_llama/utils.py", line 496, in __exit__
65.79     self.zipfile.write_end_of_file()
65.79 RuntimeError: [enforce fail at inline_container.cc:337] . unexpected pos 17973300160 vs 17973300056
------
Dockerfile:22
--------------------
  20 |     # get open-llama weights
  21 |     RUN python scripts/download.py --repo_id openlm-research/open_llama_7b --local_dir checkpoints/open-llama/7B
  22 | >>> RUN python scripts/convert_hf_checkpoint.py --checkpoint_dir checkpoints/open-llama/7B --model_size 7B
  23 |
  24 |     # Copy over single file server
--------------------
ERROR: failed to solve: process "/bin/sh -c python scripts/convert_hf_checkpoint.py --checkpoint_dir checkpoints/open-llama/7B --model_size 7B" did not complete successfully: exit code: 1
```

**Comment by msaroufim** [comment]
I've seen this error before when either the download file was corrupted or you've run out of disk. Can you try cleaning up and retrying please
